# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('last_update', models.DateTimeField(verbose_name='last update')),
                ('acquired_date', models.DateTimeField(verbose_name='date created')),
                ('text_contents', models.TextField(verbose_name='text contents')),
            ],
        ),
    ]
