# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_count',
            field=models.IntegerField(default=0, verbose_name='message_count'),
        ),
    ]
